### ISSUE TITLE
圆环图title定义数组时，前台报错

### ISSUE THREAD

**Issue by popotang78** [vueblocks/ve-charts#106]
`<ve-donut-chart :title="dayTitle" :data="dayChartData" :settings="chartSettings" :theme="ins"/>`
title如果是数组前台报错，dayChartData是计算属性
`computed: {
    dayTitle () {
      return [{
        show: true,
        text: this.epDayTotal,
        subtext: 'kWh',
        x: 'center',
        y: 'center',
        textStyle: {
          fontSize: 16,
          fontWeight: 'normal',
          color: ['#333']
        },
        subtextStyle: {
          color: '#666',
          fontSize: 12
        }
      }, {
        text: '本日用电',
        x: 'center',
        y: 'center',
        textStyle: {
          fontSize: 14,
          fontWeight: 'normal',
          color: ['#333']
        }
      }]
    },
...`

> vue.runtime.esm.js?2b0e:619 [Vue warn]: Invalid prop: type check failed for prop "title". Expected Object, got Array

**Comment by xiaoluoboding** [comment]
@popotang78 title 属性仅支持 `Object` 格式输入，参考[文档](https://echarts.apache.org/zh/option.html#title)
