### ISSUE TITLE
使用ve-charts大于0.8.2版本时启动报错

### ISSUE THREAD

**Issue by windedge** [vueblocks/ve-charts#129]
使用vue-cli创建的空白工程，使用ve-charts大于0.8.2版本时启动报错，错误信息如图：
![image](https://user-images.githubusercontent.com/27651/92848305-adc74200-f41c-11ea-9ba9-ca9a34df0b13.png)

**Comment by windedge** [comment]
这个会是什么原因？ @xiaoluoboding

**Comment by xiaoluoboding** [comment]
@windedge 请提供下运行环境，比如 vue 脚手架版本之类的

**Comment by windedge** [comment]
使用 vue init webpack vecharts-demo创建项目，
node版本：v12.16.3
yarn版本：1.22.4
nvm版本：0.35.3

**Comment by xiaoluoboding** [comment]
@windedge 建议升级 vue-cli 版本到 3+

**Comment by windedge** [comment]
vue-cli升级4.5.6后，重新执行vue-cli init webpack <dir> 还是报同样的错

**Comment by xiaoluoboding** [comment]
@windedge `vue-cli init xxx` 我记得还是用的 2.x 版本模版，新版本命令是 `vue create xxx`，参考文档：https://cli.vuejs.org/zh/guide/creating-a-project.html#vue-create
