### ISSUE TITLE
为什么隐藏legend之后上面还会留有大片空白

### ISSUE THREAD

**Issue by sukidesuka** [vueblocks/ve-charts#147]
![image](https://user-images.githubusercontent.com/63297045/114373186-edbdf580-9bb4-11eb-92bc-0b576a21669e.png)

![image](https://user-images.githubusercontent.com/63297045/114373095-d848cb80-9bb4-11eb-9729-e1163be900f5.png)

在echarts的官网发现他们也会这样留一片空白，有什么方式可以去掉吗

**Comment by sukidesuka** [comment]
已解决，需要自行设置grid属性距离边距的数值，来拉伸grid
![image](https://user-images.githubusercontent.com/63297045/114376013-d6ccd280-9bb7-11eb-8ee4-19698751a571.png)

![image](https://user-images.githubusercontent.com/63297045/114376128-ecda9300-9bb7-11eb-986f-9b3bb7884038.png)

**Comment by xiaoluoboding** [comment]
抱歉，回复晚了。ve-charts 默认提供了 grid

```js
grid: {
  right: 10,
  bottom: 10,
  left: 10,
  containLabel: true
}
```
