### ISSUE TITLE
Cannot read property 'graphic' of undefined

### ISSUE THREAD

**Issue by alenliao** [vueblocks/ve-charts#165]
您好，我用的是"echarts": "^5.1.2","ve-charts": "^0.9.10"，然后报：Uncaught TypeError: Cannot read property 'graphic' of undefined，想问一下应该怎么解决。

**Comment by yukiSolo** [comment]
VeCharts 是基于 Vue2.x 与ECharts4.x 构建封装的组件库

**Comment by alenliao** [comment]
> VeCharts 是基于 Vue2.x 与ECharts4.x 构建封装的组件库

我用命令：npm i ve-charts echarts -S 安装成功时，给我装的ECharts版本是5.1.2的，我手动降回4.9.0就没有这个错误了。
