### ISSUE TITLE
什么时候可以支持vue3版本呢？

### ISSUE THREAD

**Issue by yiweizhi** [vueblocks/ve-charts#178]

**Comment by xiaoluoboding** [comment]
@yiweizhi ECharts 5.x for Vue.js 3.x in next version. https://github.com/vueblocks/ve-charts/tree/next

**Comment by yiweizhi** [comment]
@xiaoluoboding 好的，后面会有这个版本的示例网站吗？

**Comment by xiaoluoboding** [comment]
> @xiaoluoboding 好的，后面会有这个版本的示例网站吗？

会有的，@zimuZhao 会跟进
