### ISSUE TITLE
如何动态更新数据？

### ISSUE THREAD

**Issue by RingoTC** [vueblocks/ve-charts#96]
文档里并没有提到这个部分，我需要在页面加载之后异步地获取数据，然后再加载到图表上。

**Comment by lliiuu** [comment]
你好，你怎么解决的，我也遇到一样的问题了，怎么动态改变数据

**Comment by RingoTC** [comment]
直接更新存儲數據的變量，似乎就可以。
已經很長時間沒有用過這個項目了，記憶不是特別清楚。

**Comment by xiaoluoboding** [comment]
@lliiuu 数据的动态更新，需要 **定时** 去获取异步数据，更改 `data` 的值
